# This file was auto-generated by Fern from our API Definition.

from .types import (
    CreateVoiceResponse,
    GetVoiceByIdResponse,
    ListVoicesResponse,
    TextToSpeechFromPromptResponse,
    TextToSpeechResponse,
    UpdateVoiceResponse,
    Voice,
)
from . import text_to_speech, voices
from .environment import DeeptuneEnvironment
from .version import __version__

__all__ = [
    "CreateVoiceResponse",
    "DeeptuneEnvironment",
    "GetVoiceByIdResponse",
    "ListVoicesResponse",
    "TextToSpeechFromPromptResponse",
    "TextToSpeechResponse",
    "UpdateVoiceResponse",
    "Voice",
    "__version__",
    "text_to_speech",
    "voices",
]
